### ISSUE TITLE
tping crashes when dig returns multiple IPs

### ISSUE THREAD

**Issue by schwupp** [schwupp/tping#10]
tping is not prepared when DNS resolution returns multiple IP addresses for a given hostname. most situations i can think of this must be a misconfiguration out of tping-scope (IPv4), but in IPv6 might be ok. How should we deal with it in general? crashing is no option :-)

test-host has 2 IPv6 addresses
```
$ host test
test.fritz.box has IPv6 address 2001:9e8:892f:fb00:48f:e325:6688:c293
test.fritz.box has IPv6 address 2001:9e8:892f:fb00:c54:6dc:7889:422f
```
tping crashes, because ping is given two destination parameters which is ambigous, so ping command fails multiple times
```
$ tping.sh -d test
	####### DEBUG #######
	os = [ linux-gnu ]
	args = [ 2 ]
	deadtime  = [ 1 ]
	interval = [ 1 ]
	fuzzy = [ 0 ]
	follow = [ 1 ]
	host = [ test ]
	ip = [ 2001:9e8:892f:fb00:48f:e325:6688:c293
2001:9e8:892f:fb00:c54:6dc:7889:422f ]
	ping command = [ ping -W 1 -c 1 2001:9e8:892f:fb00:48f:e325:6688:c293
2001:9e8:892f:fb00:c54:6dc:7889:422f ]
	####### DEBUG #######

Usage
  ping [options] <destination>

Options:
  <destination>      dns name or ip address
  -a                 use audible ping
  -A                 use adaptive ping
  -B                 sticky source address
  -c <count>         stop after <count> replies
  -D                 print timestamps
...
[output omitted]
...
```

first brainstorming, list is sorted: user friendlyness as well as implementation hassle ascending

1. just exit tping and throw error message
2. take the first entry, no matter what second/third entry is
3. prompt user that we found multiple DNS entries and which entry to use for tping

**Comment by lippl** [comment]
So I would not just take any entry. For now I would go with the info message to select one specific address from the list and quit
If time allows the promt would be the best option for interactive use, however I do not know if the tool is used in scripted/automated scenarios where no interaction is possible!?
