### ISSUE TITLE
Problems when receiving Type3/Code1 "Destination host unreachable"

### ISSUE THREAD

**Issue by schwupp** [schwupp/tping#5]
Trigger: tping an address which produces T1/C1 message, typically a free IP in a home network, so router sends T1/C1. Issue may be present with other return values.

observation: tping starts with "down" and then toggles between "up" and "down"

expected: tping should hold the "down" status and ignore ICMP messages other than "echo reply"

**Comment by schwupp** [comment]
https://github.com/schwupp/tping/pull/4/commits/f7b3213c4994dafdda18e8078a0cef6d0c6c62b3 has broken the logic, because a T1/C1 message looks - on a linux machine - like:
From 192.168.1.81 icmp_seq=1 Destination Host Unreachable

and therefore triggering for host up.

i think we need a if/else switch for OS selection

**Comment by schwupp** [comment]
i collected following outputs:

**linux debian 11.6**
64 bytes from <IP-of-ping'd host>: icmp_seq=1 ttl=64 time=1.25 ms
and
From <IP-of-DefGW> icmp_seq=3 Destination Host Unreachable

**macOS 12.3 / 12.6.3 / 13.2**
64 bytes from <IP-of-ping'd host>: icmp_seq=0 ttl=248 time=14.431 ms
and
Request timeout for icmp_seq 0

So from this perspective, the old 'bytes from' seems to work fine. @lippl do you know, what exactly caused your change in https://github.com/schwupp/tping/pull/4?

If 'bytes from' is still bad, maybe grepping for 'icmp_seq=.*time=' should also to the trick for both worlds?

**Comment by lippl** [comment]
As the commit describes itself: _on host unreachable macOS also prints bytes, therefore falsely detecting an ok. now matching on "icmp_seq="_ it basically caused the same behaviour on macOS as it now causes for you on linux. I just did not find the correct common string to gre for. Your suggested pattern does work for both though! 👍

**Comment by schwupp** [comment]
crazy. in my tests mac does not print "bytes from", it rather prints "icmp_seq" on a T1/C1, so your initial fix wouldn't have fixed it on mac, too. but as this is only a test-box, we will trust your real mac! i will use #8 to hopefully fix it finally ;-)

**Comment by schwupp** [comment]
had to re-open issue because of a force-push of main branch
